### PR TITLE
Message spoilers

### LINKED ISSUE #152: Implement message spoilers
Spoilers aren't implemented in gtkcord4 yet, even though they were implemented in gtkcord3.

There are 2 main approaches:

1. Attach an EventController to check for mouse hovering events, if the mouse is hovering over the spoiled text span then reveal it, or
2. Add a button that reveals the text when pressed.

1 is a lot harder since I've yet to figure out the right API to use for this. 2 is a lot easier, but it's a lot less convenient too.

### PR DESCRIPTION
**Pull request by tfuxu**
This PR implements custom Spoiler widget used as a overlay on messages wrapped in `||` tags.

**Note**: Putting this as a draft for now, as there are a couple `MarkdownViewer` bugs that needs to be fixed beforehand, and the current spoiler style definitely needs some polishing.

Fixes #152

### TODO:
- [ ] Make spoiler overlay the same size as the message text
- [ ] Refine spoiler style

#### Simple message hidden:
Screenshot from 2023-10-11 19-24-18

#### Simple message visible:
Screenshot from 2023-10-11 19-25-43

#### Textblock/multi-line message hidden:
Screenshot from 2023-10-11 19-24-30

### CODE REVIEW

**Comment by diamondburned** [comment]
Does this not work for inline spoiler tags, e.g. `hello ||world||`?

**Comment by tfuxu** [comment]
> Does this not work for inline spoiler tags, e.g. `hello ||world||`?

Ah, I completely forgot about this 🤦‍♂️️ I'll think of another solution for this, since the overlay probably isn't as flexible to put only on a specific section of the message (at least not with the current implementation).

**Comment by diamondburned** [comment]
You can use a hover/tap `EventController` combined with [`method.TextView.get_iter_at_position`](https://docs.gtk.org/gtk4/method.TextView.get_iter_at_position.html) to obtain the character mark at the hovering point, then check if it has a spoiler tag and set its opacity to 1 if there is any.

You'll also need to keep a last spoiler tag:

```go
var lastSpoilerTag *gtk.TextTag
func(spoilerTag *gtk.TextTag) { // callback
    if lastSpoilerTag == spoilerTag {
        return
    }

    if lastSpoilerTag != nil {
        lastSpoilerTag.SetProperty("opacity", 0)
    }

    spoilerTag.SetProperty("opacity", 1)
}
```

**Comment by diamondburned** [comment]
Partially implemented in https://github.com/diamondburned/dissent/commit/a52c614ea157324770a72333a61ede960365bafb.

**Comment by tfuxu** [comment]
Cool! Closing as there is a new implementation already in code. I've also created a tracking issue for currently unsupported types of spoilers #282

**Pull request closed without merging**
