### PR TITLE
Fix inconsistent capitalization in app ID

### PR DESCRIPTION
**Pull request by tfuxu**
Sorry for not noticing that before, but Flathub's backend cares about capitalization in application ID. It needs to be the same throughout the codebase, otherwise `appstreamcli` will error out with _very_ helpful `filters-but-no-output` error. 

This PR should fix issues with app ID and hopefully make `appstreamcli` happy.

### CODE REVIEW

**Comment by diamondburned** [comment]
Wouldn't `so.libdb.dissent` be the right capitalization? Or does Flatpak want a capitalized D?

**Comment by tfuxu** [comment]
There aren't any mentions about capitalization of the app name part in Flathub [docs](https://docs.flathub.org/docs/for-app-authors/requirements#application-id), so I guess it doesn't matter

**Comment by diamondburned** [comment]
I personally prefer the `so.libdb.dissent`, could you update the PR to contain that?

**Comment by tfuxu** [comment]
@diamondburned Updated

**Review by diamondburned — APPROVED** [review]

**Pull request merged**
